.PHONY: clean All

All:
	@echo "----------Building project:[ cpp - Debug ]----------"
	@cd "cpp" && "$(MAKE)" -f  "cpp.mk"
clean:
	@echo "----------Cleaning project:[ cpp - Debug ]----------"
	@cd "cpp" && "$(MAKE)" -f  "cpp.mk" clean
